<?php
/**
 * Copyright © MagePal LLC. All rights reserved.
 * See COPYING.txt for license details.
 * https://www.magepal.com | support@magepal.com
 */

/** @var $block MagePal\EditOrderEmail\Block\Adminhtml\Email\Edit */
?>
<div id="mp_edit_order_email" style="display: none">
    <form class="form change-order-email"
          novalidate
          action="<?= $block->escapeUrl($block->getAdminPostUrl()) ?>"
          method="post"
          data-mage-init='{"validation": {"errorClass": "mage-error"}}' >
        <div class="wrapper">
            <p><?php echo __('Please enter the new email address') ?></p>
            <input type="hidden" name="order_id" value="<?php echo $block->getOrderId() ?>" />
            <input type="hidden" name="old_email" value="<?php echo $block->getEmailAddress() ?>" />
            <input name="email" type="email" class="admin__control-text  data-grid-search-control"
                   placeholder="<?= $block->escapeHtml(__('Enter email address')) ?>"
                   data-validate="{required:true, 'validate-email':true}"
                   value="" />

            <div class="checkbox">
                <input type="checkbox" class="checkbox" id="assign_to_another_customer" name="assign_to_another_customer" value="1" <?= $block->getAutocheckAssignToAnotherCustomerFlag() == 1 ? 'checked' : '' ?>>
                <label for="assign_to_another_customer"><?php echo __('Assign to another customer if it exists') ?></label>
            </div>
            <?php if ($block->hasCustomerId()) : ?>
            <div class="checkbox">
                <input type="checkbox" class="checkbox" id="create_new_customer" name="create_new_customer" value="1" <?= $block->getAutocheckCreateNewCustomerFlag() == 1 ? 'checked' : '' ?>>
                <label for="create_new_customer"><?php echo __('Create new customer') ?></label>
            </div>
            <?php endif; ?>

            <div class="msg">
                <span class="mage-error"></span>
            </div>

            <div class="actions">
                <button class="action change-email primary" title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" type="button">
                    <span><?= $block->escapeHtml(__('Change Email')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "magePalEditOrderEmail": {
                "postUrl":"<?php echo $block->getAdminPostUrl() ?>",
                "buttonLabel":"<?php echo __('edit') ?>"
            }
        }
    }
</script>
